// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6milTkXhrYUqvRCkxG8l-0WABdtgj3KA',
    appId: '1:169354346218:web:d7102a85b2ad9fe506a193',
    messagingSenderId: '169354346218',
    projectId: 'aplikasi-donor-darah-59dcc',
    authDomain: 'aplikasi-donor-darah-59dcc.firebaseapp.com',
    storageBucket: 'aplikasi-donor-darah-59dcc.firebasestorage.app',
    measurementId: 'G-Z9RKCGX34J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5UB7asuhVJjq0MSYNr7iekMq7QeNSS2o',
    appId: '1:169354346218:android:f10ebefcd13b1e6c06a193',
    messagingSenderId: '169354346218',
    projectId: 'aplikasi-donor-darah-59dcc',
    storageBucket: 'aplikasi-donor-darah-59dcc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAv-ie1h5RUI8d2bG0_6aut9Eef3Ct0Lg',
    appId: '1:169354346218:ios:2474059413755b0206a193',
    messagingSenderId: '169354346218',
    projectId: 'aplikasi-donor-darah-59dcc',
    storageBucket: 'aplikasi-donor-darah-59dcc.firebasestorage.app',
    iosBundleId: 'com.example.donor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAv-ie1h5RUI8d2bG0_6aut9Eef3Ct0Lg',
    appId: '1:169354346218:ios:2474059413755b0206a193',
    messagingSenderId: '169354346218',
    projectId: 'aplikasi-donor-darah-59dcc',
    storageBucket: 'aplikasi-donor-darah-59dcc.firebasestorage.app',
    iosBundleId: 'com.example.donor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6milTkXhrYUqvRCkxG8l-0WABdtgj3KA',
    appId: '1:169354346218:web:f80de92af6cb754906a193',
    messagingSenderId: '169354346218',
    projectId: 'aplikasi-donor-darah-59dcc',
    authDomain: 'aplikasi-donor-darah-59dcc.firebaseapp.com',
    storageBucket: 'aplikasi-donor-darah-59dcc.firebasestorage.app',
    measurementId: 'G-Y7DC9FK5LH',
  );

}